# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69efe02bc81fcee444eeaafd287790b8bfde0377e52b6e0857db6d61381ac7ac4d33b1d5e3af7c80d123fa2d3de5d7726afc7ceafff2a31bc769ac4dbb6dcc51

test:
  secret_key_base: 471f152c292d2e6cc4817ba2b864a4771afd67d3e501646f3938fff326264a9fb404d902d30fcecaadc7a4534edf1e9854e4cc9ba4de93f851a21502672083aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
